// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-BdRfgBkN2kjMTcSwgYscFZJq1hiqaic',
    appId: '1:949830857474:web:dbe66e4e5b192b4610881b',
    messagingSenderId: '949830857474',
    projectId: 'instaclone-b51b8',
    authDomain: 'instaclone-b51b8.firebaseapp.com',
    storageBucket: 'instaclone-b51b8.appspot.com',
    measurementId: 'G-X673QWV2XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3icg4NYeiHTXXLDgomfAVCTgNPH60neg',
    appId: '1:949830857474:android:24bb9a52341a9de110881b',
    messagingSenderId: '949830857474',
    projectId: 'instaclone-b51b8',
    storageBucket: 'instaclone-b51b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDzLshsTnrWm9ka-hjn-CHXybmy0bm6vU',
    appId: '1:949830857474:ios:61fa0e8c51ed4fca10881b',
    messagingSenderId: '949830857474',
    projectId: 'instaclone-b51b8',
    storageBucket: 'instaclone-b51b8.appspot.com',
    iosClientId: '949830857474-v2om4o3v7sis8kagl4hg1c7keabs53rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDzLshsTnrWm9ka-hjn-CHXybmy0bm6vU',
    appId: '1:949830857474:ios:86574fe56bdd94c510881b',
    messagingSenderId: '949830857474',
    projectId: 'instaclone-b51b8',
    storageBucket: 'instaclone-b51b8.appspot.com',
    iosClientId: '949830857474-nmvc71em18atnjopjir632jr94ipoc8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaclone.RunnerTests',
  );
}
